/**
 * The built-in word pairs, used until a list is uploaded in Settings.
 *
 * Written for this app in the style of the classic game: two everyday things
 * close enough that a one-word clue could fit either, far enough that a few
 * rounds of clues pull them apart. Which side the civilians get is decided at
 * deal time, so the order within a pair doesn't matter.
 */

import type { WordPair } from './types';

const PAIRS: ReadonlyArray<readonly [string, string]> = [
  // food & drink
  ['Coffee', 'Tea'],
  ['Pizza', 'Burger'],
  ['Sushi', 'Sashimi'],
  ['Ketchup', 'Mustard'],
  ['Pancake', 'Waffle'],
  ['Butter', 'Cheese'],
  ['Honey', 'Jam'],
  ['Chocolate', 'Candy'],
  ['Ice cream', 'Frozen yogurt'],
  ['Donut', 'Bagel'],
  ['Cookie', 'Brownie'],
  ['Muffin', 'Cupcake'],
  ['Apple', 'Pear'],
  ['Lemon', 'Lime'],
  ['Strawberry', 'Raspberry'],
  ['Watermelon', 'Melon'],
  ['Mango', 'Papaya'],
  ['Cherry', 'Grape'],
  ['Fries', 'Chips'],
  ['Rice', 'Quinoa'],
  ['Spaghetti', 'Macaroni'],
  ['Soup', 'Stew'],
  ['Sandwich', 'Wrap'],
  ['Taco', 'Burrito'],
  ['Samosa', 'Spring roll'],
  ['Milk', 'Yogurt'],
  ['Beer', 'Wine'],
  ['Juice', 'Smoothie'],
  ['Coca-Cola', 'Pepsi'],
  ['Popcorn', 'Nachos'],
  ['Salt', 'Sugar'],
  ['Pepper', 'Chilli'],
  ['Omelette', 'Scrambled eggs'],
  ['Chicken', 'Turkey'],
  ['Bread', 'Toast'],

  // animals
  ['Cat', 'Dog'],
  ['Lion', 'Tiger'],
  ['Wolf', 'Fox'],
  ['Horse', 'Donkey'],
  ['Rabbit', 'Hamster'],
  ['Dolphin', 'Shark'],
  ['Octopus', 'Squid'],
  ['Eagle', 'Hawk'],
  ['Owl', 'Bat'],
  ['Penguin', 'Polar bear'],
  ['Crocodile', 'Alligator'],
  ['Frog', 'Toad'],
  ['Butterfly', 'Moth'],
  ['Bee', 'Wasp'],
  ['Ant', 'Spider'],
  ['Snake', 'Lizard'],
  ['Cow', 'Buffalo'],
  ['Sheep', 'Goat'],
  ['Monkey', 'Gorilla'],
  ['Elephant', 'Rhino'],
  ['Giraffe', 'Zebra'],
  ['Duck', 'Goose'],
  ['Parrot', 'Pigeon'],
  ['Mouse', 'Rat'],
  ['Turtle', 'Tortoise'],
  ['Deer', 'Moose'],
  ['Camel', 'Llama'],

  // places
  ['Beach', 'Pool'],
  ['Hotel', 'Hostel'],
  ['Hospital', 'Clinic'],
  ['School', 'College'],
  ['Library', 'Bookstore'],
  ['Museum', 'Art gallery'],
  ['Cinema', 'Theatre'],
  ['Airport', 'Train station'],
  ['Mall', 'Market'],
  ['Restaurant', 'Cafe'],
  ['Gym', 'Spa'],
  ['Zoo', 'Aquarium'],
  ['Park', 'Garden'],
  ['Farm', 'Village'],
  ['Castle', 'Palace'],
  ['Mountain', 'Hill'],
  ['Forest', 'Jungle'],
  ['River', 'Lake'],
  ['Cave', 'Tunnel'],
  ['City', 'Town'],
  ['Prison', 'Police station'],
  ['Office', 'Factory'],
  ['Bank', 'ATM'],
  ['Bedroom', 'Living room'],
  ['Stadium', 'Playground'],
  ['Circus', 'Theme park'],

  // getting around
  ['Car', 'Van'],
  ['Bus', 'Tram'],
  ['Train', 'Metro'],
  ['Bicycle', 'Motorcycle'],
  ['Plane', 'Helicopter'],
  ['Boat', 'Ship'],
  ['Scooter', 'Skateboard'],
  ['Truck', 'Tractor'],
  ['Rocket', 'Satellite'],
  ['Ambulance', 'Fire truck'],
  ['Uber', 'Taxi'],

  // around the house
  ['Pen', 'Pencil'],
  ['Book', 'Magazine'],
  ['Chair', 'Sofa'],
  ['Bed', 'Hammock'],
  ['Pillow', 'Blanket'],
  ['Fork', 'Spoon'],
  ['Knife', 'Scissors'],
  ['Mug', 'Glass'],
  ['Plate', 'Bowl'],
  ['Fridge', 'Freezer'],
  ['Oven', 'Microwave'],
  ['Lamp', 'Candle'],
  ['Mirror', 'Window'],
  ['Door', 'Gate'],
  ['Key', 'Lock'],
  ['Clock', 'Watch'],
  ['Umbrella', 'Raincoat'],
  ['Wallet', 'Purse'],
  ['Backpack', 'Suitcase'],
  ['Toothbrush', 'Comb'],
  ['Soap', 'Shampoo'],
  ['Towel', 'Tissue'],
  ['Shower', 'Bathtub'],
  ['Broom', 'Vacuum cleaner'],
  ['Hammer', 'Screwdriver'],
  ['Ladder', 'Stairs'],
  ['Balloon', 'Kite'],
  ['Envelope', 'Postcard'],
  ['Glue', 'Tape'],
  ['Map', 'Compass'],
  ['Telescope', 'Microscope'],

  // clothes & things you wear
  ['Shirt', 'T-shirt'],
  ['Jeans', 'Trousers'],
  ['Dress', 'Skirt'],
  ['Shoes', 'Sandals'],
  ['Boots', 'Sneakers'],
  ['Hat', 'Cap'],
  ['Scarf', 'Tie'],
  ['Gloves', 'Socks'],
  ['Jacket', 'Sweater'],
  ['Sunglasses', 'Glasses'],
  ['Necklace', 'Bracelet'],
  ['Ring', 'Earrings'],
  ['Pyjamas', 'Tracksuit'],

  // tech, brands & screen
  ['iPhone', 'Samsung'],
  ['Laptop', 'Tablet'],
  ['Facebook', 'Instagram'],
  ['WhatsApp', 'Telegram'],
  ['YouTube', 'Netflix'],
  ['Google', 'Bing'],
  ['Email', 'Letter'],
  ['TV', 'Radio'],
  ['Headphones', 'Earbuds'],
  ['Speaker', 'Microphone'],
  ['Printer', 'Scanner'],
  ['Camera', 'Webcam'],
  ['Nike', 'Adidas'],
  ['Amazon', 'Flipkart'],
  ["McDonald's", 'KFC'],
  ['Batman', 'Superman'],
  ['Spider-Man', 'Iron Man'],
  ['Harry Potter', 'Percy Jackson'],
  ['Mickey Mouse', 'Donald Duck'],
  ['Star Wars', 'Star Trek'],
  ['Lego', 'Jigsaw puzzle'],

  // sport & games
  ['Football', 'Rugby'],
  ['Cricket', 'Baseball'],
  ['Tennis', 'Badminton'],
  ['Basketball', 'Volleyball'],
  ['Chess', 'Checkers'],
  ['Golf', 'Hockey'],
  ['Swimming', 'Diving'],
  ['Boxing', 'Wrestling'],
  ['Skiing', 'Snowboarding'],
  ['Running', 'Cycling'],
  ['Yoga', 'Pilates'],
  ['Cards', 'Dice'],
  ['Karaoke', 'Dancing'],
  ['Olympics', 'World Cup'],

  // people & characters
  ['Doctor', 'Nurse'],
  ['Teacher', 'Professor'],
  ['Police', 'Soldier'],
  ['Pilot', 'Astronaut'],
  ['Chef', 'Waiter'],
  ['Singer', 'Rapper'],
  ['Actor', 'Model'],
  ['Lawyer', 'Judge'],
  ['Farmer', 'Gardener'],
  ['Firefighter', 'Lifeguard'],
  ['Painter', 'Photographer'],
  ['Dentist', 'Barber'],
  ['King', 'Prince'],
  ['Pirate', 'Ninja'],
  ['Vampire', 'Zombie'],
  ['Witch', 'Wizard'],
  ['Ghost', 'Skeleton'],
  ['Robot', 'Alien'],
  ['Santa Claus', 'Easter Bunny'],
  ['Brother', 'Cousin'],
  ['Boyfriend', 'Husband'],
  ['Magician', 'Clown'],

  // nature & weather
  ['Sun', 'Moon'],
  ['Star', 'Planet'],
  ['Rain', 'Snow'],
  ['Thunder', 'Lightning'],
  ['Tornado', 'Hurricane'],
  ['Rainbow', 'Sunset'],
  ['Cloud', 'Smoke'],
  ['Fire', 'Volcano'],
  ['Rose', 'Tulip'],
  ['Tree', 'Cactus'],
  ['Waterfall', 'Fountain'],
  ['Summer', 'Winter'],
  ['Spring', 'Autumn'],
  ['Morning', 'Evening'],

  // occasions & feelings
  ['Birthday', 'Wedding'],
  ['Christmas', 'New Year'],
  ['Halloween', 'Carnival'],
  ['Holiday', 'Weekend'],
  ['Dream', 'Nightmare'],
  ['Party', 'Picnic'],
  ['Concert', 'Festival'],
  ['Exam', 'Interview'],
  ['Kiss', 'Hug'],
  ['Laugh', 'Smile'],
  ['Crush', 'Date'],
  ['Money', 'Credit card'],
  ['Diamond', 'Pearl'],
];

export const BUILT_IN_PAIRS: readonly WordPair[] = PAIRS.map(([civilianWord, undercoverWord]) => ({
  civilianWord,
  undercoverWord,
}));
